export enum ActionType {
  SAVE_VERSION = 'SAVE_VERSION',
  SAVE_SEED = 'SAVE_SEED',
  CLEAR_SEED = 'CLEAR_SEED',
  SAVE_WALLET = 'SAVE_WALLET',
  CLEAR_WALLET = 'CLEAR_WALLET',
  SET_BALANCE = 'SET_BALANCE',
  CLEAN_BALANCE = 'CLEAN_BALANCE',
  SET_DELEGATES = 'SET_DELEGATES'
}
