export enum ActionType {
  SAVE_VERSION = 'SAVE_VERSION',
  SAVE_INFO = 'SAVE_INFO',
  SAVE_SEED = 'SAVE_SEED',
  CLEAR_SEED = 'CLEAR_SEED',
  SAVE_WALLET = 'SAVE_WALLET',
  CLEAR_WALLET = 'CLEAR_WALLET',
  SET_BALANCE = 'SET_BALANCE',
  CLEAN_BALANCE = 'CLEAN_BALANCE',
  SET_DELEGATES = 'SET_DELEGATES',
  SET_APPEND_TO_DELEGATES = 'SET_APPEND_TO_DELEGATES',
  SET_CASTED_VOTES_DELEGATES = 'SET_CASTED_VOTES_DELEGATES',
  SET_APPEND_TO_CASTED_VOTES_DELEGATES = 'SET_APPEND_TO_CASTED_VOTES_DELEGATES',
  SET_TRANSACTIONS = 'SET_TRANSACTIONS',
  SET_APPEND_TO_TRANSACTIONS = 'SET_APPEND_TO_TRANSACTIONS'
}
